#!@python3@/bin/python
# code: language=python tabSize=4

import json
import subprocess
import urllib.request

def fetchKeys(user: str, url: str) -> []:
    if url == "MANUAL":
      keys = data["keys"][user]
    else:
      keys = [
          x.strip() for x in
          urllib.request \
              .urlopen(url) \
              .read() \
              .decode("UTF-8") \
              .split("\n")
          if x.strip() != ""
      ]
    print(f"{user}:\t{len(keys)}")
    return keys

filename = "authorizedKeys.nix"

data = json.loads(
  subprocess.check_output(["@nixFlakes@/bin/nix", "eval", "--json", "-f", filename])
)

data["keys"] = {
    user: fetchKeys(user, url) for (user,url) in data["users"].items()
}

nix = subprocess.check_output(
  ["@nixfmt@/bin/nixfmt"],
  input = subprocess.check_output(
    ["@nixFlakes@/bin/nix", "eval", "--impure", "--expr", "builtins.fromJSON (builtins.readFile \"/dev/stdin\")"],
    input=json.dumps(data).encode("UTF-8")
  )
).decode("UTF-8")

with open(filename, "w") as f:
    f.write(nix)
    f.flush()
